name: client_tggt
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.4.0

environment:
  sdk: ">=2.12.0 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  animated_text_kit: ^4.2.1
  auto_route: ^4.0.1
  auto_size_text: ^3.0.0
  badges: ^2.0.2
  bot_toast: ^4.0.1
  cached_network_image: ^3.2.0
  carousel_slider: ^4.0.0
  chewie: ^1.2.2
  cupertino_icons: ^1.0.2
  date_picker_timeline: ^1.2.3
  dio: ^4.0.4
  dropdown_button2: ^1.0.6
  dropdown_search: ^2.0.1
  expandable: ^5.0.1
  expandable_bottom_sheet: ^1.1.1+1
  firebase_core: ^1.17.1
  firebase_dynamic_links: ^4.2.5
  firebase_messaging: ^11.4.1
  app_settings: ^4.1.6
  flag: ^5.0.2
  flutter:
    sdk: flutter
  flutter_animation_progress_bar: ^2.0.1
  flutter_chat_ui: ^1.5.3
  flutter_datetime_picker: ^1.5.1
  flutter_dynamic_icon: ^2.0.0
  flutter_easyloading: ^3.0.3
  flutter_form_builder: ^7.0.0
  flutter_keyboard_visibility: ^5.1.0
  flutter_launcher_icons: ^0.9.2
  flutter_local_notifications: ^9.5.3+1
  flutter_native_timezone: ^2.0.0
  flutter_rating_bar: ^4.0.1
  flutter_screenutil: ^5.0.0+2
  flutter_spinkit: ^5.1.0
  flutter_staggered_grid_view: ^0.4.1
  flutter_svg: ^1.0.0 
  flutter_vector_icons: ^1.0.0
  folding_cell: ^1.0.2
  geocode: ^1.0.1
  geocoding: ^2.0.4
  get: ^4.3.8
  get_it: ^7.2.0
  get_storage: ^2.0.3
  getwidget: ^2.0.4
  google_fonts: ^2.1.0
  google_maps_flutter: ^2.1.1
  hexcolor: ^2.0.5
  http: ^0.13.4
  image: ^3.0.8
  image_picker: ^0.8.4+4
  image_save: ^5.0.0
  indexed: ^0.0.6
  intl: ^0.17.0
  json_annotation: ^4.4.0
  loading_overlay: ^0.3.0
  location: ^4.3.0
  logging: ^1.0.2
  lottie: ^1.2.1
  numberpicker: ^2.1.1
  path: ^1.8.0
  path_provider: ^2.0.7
  permission_handler: ^8.3.0
  pretty_dio_logger: ^1.1.1
  pull_to_refresh: ^2.0.0
  qr_flutter: ^4.0.0
  retrofit: ^3.0.0
  shimmer: ^2.0.0
  socket_io_client: ^2.0.0-beta.4-nullsafety.0
  story_view: ^0.13.2
  table_calendar: ^3.0.3
  timeago: ^3.1.0
  timelines: ^0.1.0
  url_launcher: ^6.0.18
  video_player: ^2.2.10
  video_thumbnail: ^0.4.3
  webview_flutter: ^3.0.0
  modal_bottom_sheet: ^2.0.0
  google_maps_place_picker_mb: ^2.0.0-mb.10
  place_picker: ^0.9.19
  syncfusion_flutter_charts: ^19.4.52
  percent_indicator: ^4.0.0
  syncfusion_flutter_datepicker: ^19.4.52
  pin_code_fields: ^7.4.0
  screenshot: ^1.2.3
  image_gallery_saver: ^1.7.1
  share_plus: ^4.0.5
  flutter_sticky_header: ^0.6.1
  flutter_polyline_points: ^1.0.0
  new_version: ^0.3.0
  qr_code_scanner:
    git:
      url: https://github.com/xeinebiu/qr_code_scanner.git
      ref: fix_break_changes_platform

dev_dependencies:
  auto_route_generator: ^4.0.0
  build_runner: ^2.1.4
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.0.1
  retrofit_generator: any

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon-red.png"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:ß
  assets:
    - assets/images/
    - assets/images/category/
    - assets/images/place/
    - assets/images/splash/
    - assets/images/affiliate/
    - assets/images/bar/
    - assets/images/attribute/
    - assets/images/error/
    - assets/images/logo/
    - assets/images/theme/
    - assets/images/banner/
    - assets/images/rewards/
    - assets/images/auth/
    - assets/images/vendors/dashboard/
    - assets/images/membership/Member-card 1.png
    - assets/posts.json
    - assets/comments.json
    - assets/messages.json
    - assets/provinces.json
    - assets/loading/laka_loading.json
    - assets/loading/fivestar.json
    - assets/loading/images/

    # - assets/images/bottom_icon/
    - assets/images/vendors/
    #- assets/images/massage/
    #- assets/images/restaurant/
    - assets/icons/
    - assets/icon/
    - assets/splash/
    - assets/splash/images/
    - assets/map_style.txt
    - assets/map_style_dark.txt
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/SVN-Poppins-Regular.ttf
        - asset: assets/fonts/Poppins/SVN-Poppins-Black.ttf
        - asset: assets/fonts/Poppins/SVN-Poppins-Light.ttf
        - asset: assets/fonts/Poppins/SVN-Poppins-Medium.ttf
          weight: 400
        - asset: assets/fonts/Poppins/SVN-Poppins-SemiBold.ttf
          weight: 500
        - asset: assets/fonts/Poppins/SVN-Poppins-Bold.ttf
          weight: 700
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    invalid_annotation_target: ignore
