// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAM0VX0VWhGlCe4IFghBOlvlD_AvL65agE',
    appId: '1:447554380732:android:74fccd33899e4d226601b9',
    messagingSenderId: '447554380732',
    projectId: 'laka-vn',
    storageBucket: 'laka-vn.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSDs43iiPK_mkqFca8UpIDPcXMEzaYctg',
    appId: '1:447554380732:ios:58f2877b936697266601b9',
    messagingSenderId: '447554380732',
    projectId: 'laka-vn',
    storageBucket: 'laka-vn.appspot.com',
    androidClientId:
        '447554380732-mil7ndpksjmboqi3vsr7nmkjou8v9p8d.apps.googleusercontent.com',
    iosClientId:
        '447554380732-fi1t5afai74jbe4gvgn7atbe0d13081q.apps.googleusercontent.com',
    iosBundleId: 'vn.com.laka.mobile',
  );
}
